=== EffectiveRange/raspbian-image-repository/schema/target-config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "reference": {
        "type": "string"
      },
      "sources": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "source": {
              "type": "string"
            },
            "key_id": {
              "type": "string"
            },
            "key_file": {
              "type": "string"
            },
            "key_server": {
              "type": "string"
            }
          },
          "required": ["name", "source", "key_id", "key_file"]
        }
      },
      "packages": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "package": {
              "type": "string"
            },
            "release": {
              "type": "object",
              "properties": {
                "owner": {
                  "type": "string"
                },
                "repo": {
                  "type": "string"
                },
                "tag": {
                  "type": "string"
                },
                "matcher": {
                  "type": "string"
                }
              },
              "required": ["owner", "repo", "matcher"]
            },
            "version": {
              "type": "string"
            },
            "file_url": {
              "type": "string"
            }
          },
          "required": ["package"]
        }
      },
      "boot_cmdline": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "boot_config": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "first_boot": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "pre_install": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "post_install": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": ["name", "version", "reference", "packages"]
  }
}

=== EffectiveRange/raspbian-image-repository/config/target-config.json
[
  {
    "name": "scarecrow-base",
    "version": "1.3.0",
    "reference": "2024-11-19-raspios-bookworm-armhf",
    "sources": [
      {
        "name": "effective-range",
        "source": "deb http://aptrepo.effective-range.com bookworm main",
        "key_id": "C1AEE2EDBAEC37595801DDFAE15BC62117A4E0F3",
        "key_file": "http://aptrepo.effective-range.com/dists/bookworm/public.key",
        "key_server": "keyserver.ubuntu.com"
      }
    ],
    "packages": [
      {
        "package": "mrhat-pkg",
        "version": "1.2.0",
        "file_url": "https://github.com/EffectiveRange/mrhat-pkg/releases/download/v1.2.0/mrhat-pkg_1.2.0-1_all.deb"
      },
      {
        "package": "filebeat",
        "version": "8.12.2",
        "file_url": "https://github.com/EffectiveRange/elastic-beats-armhf-deb/releases/download/v8.12.2/filebeat-8.12.2-armv7l.deb"
      },
      {
        "package": "openvpn"
      },
      {
        "package": "vlc"
      },
      {
        "package": "libcamera-apps"
      }
    ],
    "boot_config": [
      "enable_uart=1",
      "dtoverlay=mrhat-battery-simple",
      "dtoverlay=mrhat-bq25622",
      "dtoverlay=mrhat-platform",
      "dtoverlay=mrhat-rx8130",
      "dtoverlay=googlevoicehat-soundcard",
      "dtoverlay=disable-bt",
      "gpio=4=op,dl",
      "gpio=5,16=ip"
    ],
    "first_boot": [
      "chown -R admin:admin /home/admin",
      "depmod",
      "reboot"
    ],
    "post_install": [
      "raspi-config nonint do_wifi_country HU",
      "raspi-config nonint do_i2c 0",
      "echo \"options brcmfmac roamoff=1\" >> /etc/modprobe.d/brcmfmac.conf",
      "mkdir -p /home/admin/.ssh",
      "echo \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICDjVgR+K957kS+WyppjP1PbQW1FBxvM2XgzwtglvHeb fecjanky@gs-p14s\" >> /home/admin/.ssh/authorized_keys",
      "chmod 600 /home/admin/.ssh/authorized_keys"
    ]
  },
  {
    "name": "edge-pi-zero",
    "version": "1.8.2",
    "reference": "2024-07-05-raspios-bullseye",
    "sources": [
      {
        "name": "effective-range",
        "source": "deb http://aptrepo.effective-range.com bullseye main",
        "key_id": "C1AEE2EDBAEC37595801DDFAE15BC62117A4E0F3",
        "key_file": "http://aptrepo.effective-range.com/dists/bullseye/public.key",
        "key_server": "keyserver.ubuntu.com"
      }
    ],
    "packages": [
      {
        "package": "i2c-tools"
      },
      {
        "package": "upower"
      },
      {
        "package": "wavemon"
      },
      {
        "package": "ntp"
      },
      {
        "package": "mrhat-pkg",
        "version": "1.1.1",
        "file_url": "https://github.com/EffectiveRange/mrhat-pkg/releases/download/v1.1.1/mrhat-pkg_1.1.1-1_all.deb"
      },
      {
        "package": "filebeat",
        "version": "8.12.2",
        "file_url": "https://github.com/EffectiveRange/elastic-beats-armhf-deb/releases/download/v8.12.2/filebeat-8.12.2-armv7l.deb"
      }
    ],
    "boot_config": [
      "enable_uart=1",
      "dtoverlay=mrhat-battery-simple",
      "dtoverlay=mrhat-bq25622",
      "dtoverlay=mrhat-platform",
      "dtoverlay=mrhat-rx8130",
      "dtoverlay=googlevoicehat-soundcard"
    ],
    "first_boot": [
      "depmod",
      "reboot"
    ],
    "post_install": [
      "raspi-config nonint do_wifi_country HU",
      "raspi-config nonint do_i2c 0"
    ]
  },
  {
    "name": "core-pi-4",
    "version": "0.2.0",
    "reference": "2024-03-12-raspios-bullseye-arm64",
    "sources": [
      {
        "name": "docker",
        "source": "deb https://download.docker.com/linux/debian bullseye stable",
        "key_id": "9DC858229FC7DD38854AE2D88D81803C0EBFCD88",
        "key_file": "https://download.docker.com/linux/debian/gpg"
      },
      {
        "name": "effective-range",
        "source": "deb http://aptrepo.effective-range.com bullseye main",
        "key_id": "C1AEE2EDBAEC37595801DDFAE15BC62117A4E0F3",
        "key_file": "http://aptrepo.effective-range.com/dists/bullseye/public.key",
        "key_server": "keyserver.ubuntu.com"
      }
    ],
    "packages": [
      {
        "package": "docker-ce"
      },
      {
        "package": "docker-ce-cli"
      },
      {
        "package": "containerd.io"
      },
      {
        "package": "docker-buildx-plugin"
      },
      {
        "package": "docker-compose-plugin"
      },
      {
        "package": "docker-ce"
      },
      {
        "package": "log-server",
        "release": {
          "owner": "EffectiveRange",
          "repo": "log-server",
          "tag": "latest",
          "matcher": "*arm64.deb"
        }
      },
      {
        "package": "apt-server",
        "release": {
          "owner": "EffectiveRange",
          "repo": "apt-server",
          "tag": "latest",
          "matcher": "*arm64.deb"
        }
      },
      {
        "package": "ansible-server",
        "release": {
          "owner": "EffectiveRange",
          "repo": "ansible-server",
          "tag": "latest",
          "matcher": "*arm64.deb"
        }
      },
      {
        "package": "filebeat",
        "version": "8.12.2",
        "file_url": "https://github.com/EffectiveRange/elastic-beats-armhf-deb/releases/download/v8.12.2/filebeat-8.12.2-arm64.deb"
      }
    ]
  }
]
